[tox]
skipdist = True
envlist = format, lint

[testenv:format]
deps = ruff==0.15.7
commands =
    ruff format app/
    ruff check --select I --fix app/

[testenv:lint]
deps = ruff==0.15.7
commands =
    ruff check app
